apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amcm-init
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomaszkiewicz/amcm-test.git
    path: .
    plugin:
      name: amcm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true

